### ISSUE TITLE
doc blocks not required for getters/setters

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/standards-php#11]

**Comment by pbergman** [comment]
what will be the rule for php <= 7  and strict typing?

**Comment by ErikTrapman** [comment]
do you mean the whole docblock, or only the function-comment ?

**Comment by muhammedeminakbulut** [comment]
I received this as to remove the getters/setters description comment in the doc block but that is already not required so I suppose it is about what `@return`.

**Comment by boudewijn-zicht** [comment]
Lets assume that this rule will need to be applicable to both php 5.6 and php 7.1.  In that case it is important that a doc block exists, for the getter the `@return` should be required and for the setter the `@param` should be required.

For php 7.1 it would be ideal if the sniffer could check if the typehint is given.  If a typehint is detected, the `@return` or `@param` should be disallowed, as it would convey exactly the same information (allowing mismatches between the two hints).  **However, lets postpone the php 7.1 specific rules for another time**

**Comment by pbergman** [comment]
i think with >= 7 this could be checked with the strict notion

**Comment by muhammedeminakbulut** [comment]
decided not to implement
