### ISSUE TITLE
disallow double newline after `{` 

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/standards-php#12]

**Comment by boudewijn-zicht** [comment]
For clarification, the proposal is to **disallow** the following:
```
function foo() { // newline
   // second, i.e. double, newline
   return 'foo';
}
```

**Comment by wtfzdotnet** [comment]
Personally I do however like to "group" conditions and setting variables and return statements within a method a bit more, although not directly related I do consider the following valid ( and I believe that is the case here );

```php
function foo() {
  $foo = 'bar';

  if ($foo !== 'bar') ...

  return $foo;
}
```

**Comment by muhammedeminakbulut** [comment]
decided to implement
