### ISSUE TITLE
add rule to restrict method length

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/standards-php#16]
long methods are really hard to understand and maintain. 

max 20 lines?

**Comment by ErikTrapman** [comment]
would a number of arguments make more sens?

**Comment by muhammedeminakbulut** [comment]
the issue with long methods is that it gets harder to understand for the maintainer and the paths that it follows are increasing in a steep way. But arguments are also a good way to restrict massive methods. Mostly long methods could be cut into smaller pieces. Makes code testable and better understandable by new people.

**Comment by DoNormal** [comment]
I'm in favor of any rule that stops mindless typing, and forces a developer to think about the structure of his code. The value might seem a bit arbitrary (is a method with 21 lines a bad method?) but the line should be drawn somewhere.

Maximum number of params is perhaps another rule/sniff.

P.S. In JavaScript, ESLint already supports this type of linting so it's not uncommon (https://eslint.org/docs/rules/max-statements)

**Comment by boudewijn-zicht** [comment]
If someone ever have the need of writing a method that has 20+ lines or 20+ parameters, then this is probably not because they think that this is a good idea.  There is probably some reason for it, i.e. legacy or something like that.

I am against enforcing this, discuss it in a PR and look at it in a case by case basis.

**Comment by muhammedeminakbulut** [comment]
people having a valid reason for long methods is really naif or a generalization of your own intend on things to other developers. Maybe its better to state I instead of someone :) When I write long methods or a lot of arguments it is mainly being lazy. Mainly not with purpose. As I have experienced long methods often contain too many paths created by If else , foreach,or switch statements. These path explosion leads to less understandable code and this affects the maintainability when the dev which created it drops out the dev team.

I think at least it's good to be warned about complex snippets. Maybe we should consider a threshold for cyclomatic complexity on methods (instead of lenght). Thats a proven measure in software development which can point out un-maintainable code.

**Comment by boudewijn-zicht** [comment]
So you are talking about the length of the entire method, including all the code?

In that case, I am definitely against limiting it.  I don't want a script to throw an error because I had to add a few lines, resulting in the length going over some given threshold.

Again, I think a human (i.e. PR) is much better at deciding things like this than a script can ever be.

**Comment by muhammedeminakbulut** [comment]
every line between the curly braces of a method. yes.

**Comment by DoNormal** [comment]
Method length or architecture is almost never discussed in a PR, so if this sniff is rejected, we'll probably resort back to never checking this. Humans are either not aware they should favor small methods over big ones, or they forget it. I'm still ❤️ing this.

**Comment by wpbenner** [comment]
As a rule of thumb, if you feel the need to comment on something inside a method, you should take this code and put it in a new method. Even a single line can and should be split off into a separate method, if it requires explanations. And if the method has a descriptive name, nobody will need to look at the code to see what it does.

**Comment by pbergman** [comment]
i think the rule should be that a function should do one thing (and could not be split up in multiple reusable or testable part) and not be any hard limit. 

Because with a function for example that will setup curl you could easy exceed you limit! (and can think of a couple more!)

**Comment by muhammedeminakbulut** [comment]
decided not to implement -> too look into other methods such as cyclomatic complexity
