### ISSUE TITLE
single or unused variables

### ISSUE THREAD

**Issue by pbergman** [zicht/standards-php#17]
disable the use of single or not used variables like:

```
.....
$foo = $this->getSomething();
return [
   'foo' => $foo,
   .........
]

```

should be:

```
.....
return [
   'foo' => $this->getSomething(),
   .........
]
```

**Comment by muhammedeminakbulut** [comment]
should this be with function calls with no arguments? Because sometimes I use this style to have a more understandable array definition when methods requiring 2 arguments or more.
```
$foo = $this->crazyMethodCall($descriptiveVarNameOne, $descriptiveVarNameTwo, $descriptiveVarNameThree);

return [
    'foo' => $foo,
];
```

**Comment by pbergman** [comment]
if `$foo` is only used there, then it should be:

```
return [
    'foo' => $this->crazyMethodCall(
    	$descriptiveVarNameOne, 
    	$descriptiveVarNameTwo, 
    	$descriptiveVarNameThree
    ),
];
```

**Comment by wpbenner** [comment]
@muhammedeminakbulut is dyadic functions then not a good standard for the example that is give by you?

**Comment by boudewijn-zicht** [comment]
There are cases where a function call has side-effects, and it is crucial that it is called before it it placed in the array.  This occurs in a few Ticketing projects where `$customer = $this->requireLoggedInCustomer()` would throw an exception, which results in an http redirect to the login page.  

Sometimes the `$customer` variable is not used in the remainder of the code until, at the end, it is passed to the template.  This rule would make this very confusing, as the 'require a customer' check should be done before any other actions are taken by the controller.

**Comment by pbergman** [comment]
so by using this rule we can already see that your function does more than it should do. If i read it right you method does authentication and authorization and in my opinion this should be separated and be handled in the security layer. By doing that it will not reach your controller at all and wont have this problem you`r describing.

Even if you want to discard the security layer (and do`nt see why because it was bould for things like this), your method would have been allot less confusing by separating the authentication and authorization (and perhaps a different method name)

**Comment by muhammedeminakbulut** [comment]
decided not to implement. readability is an important argument. by the core dev team.
