### ISSUE TITLE
Use `{@inheritdoc}` instead of other variations

### ISSUE THREAD

**Issue by boudewijn-zicht** [zicht/standards-php#20]
Using `{@inheritdoc}` in your doc-comment is understood and auto-completed by php-storm.

- :green_heart: `{@inheritdoc}`
- :red_circle: `{@inheritDoc}`
- :red_circle: `@{inheritDoc}`
- :red_circle: `@{inheritdoc}`
- :red_circle: `@inheritDoc`
- :red_circle: `@inheritdoc`

https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.inlineinheritdoc.pkg.html

**Comment by erik-zicht** [comment]
The only problem is dat `{@inheritdoc}` is not picked up by our sniffer. Maybe this can be adjusted in our code?
With `{@inheritdoc}`:
```
FILE: ...
--------------------------------------------------------------------------------
FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 15 | ERROR | Doc comment for "$form" missing
    |       | (Zicht.Commenting.FunctionComment.MissingParamTag)
--------------------------------------------------------------------------------
UPGRADE TO PHP_CODESNIFFER 2.0 TO FIX ERRORS AUTOMATICALLY
--------------------------------------------------------------------------------
```

With `{@inheritDoc}` there are no issues.

**Comment by DoNormal** [comment]
We already agreed on `@{inheritDoc}`: https://github.com/zicht/decorum/blob/ff1992a9a6090edcef3360ca6e76c5c5c65a4b0e/best-practices/php/README.md#commenting-and-documenting

**Comment by muhammedeminakbulut** [comment]
this will need also a change in the decorum and the sniff. decided to implement

**Comment by 7ochem** [comment]
`@{inheritdoc}` is not a valid PHPDoc syntax. It should be `@inheritDoc` or the inline variant `{@inheritDoc}`. Just like `@see` and its inline variant `{@see}`.

`@annotation` is single line, `{@annotation}` is the inline syntax, but `@{annotation}` is invalid.

**Comment by boudewijn-zicht** [comment]
@7ochem Perhaps you are confused by the comment from DoNormal on Nov 28.  We decided on using `{@inheritdoc}`, which is valid syntax.  This is reflected in the description of this issue.

**Comment by 7ochem** [comment]
http://docs.phpdoc.org/guides/inheritance.html ...
