### ISSUE TITLE
Usage of numbers in methodname

### ISSUE THREAD

**Issue by wtfzdotnet** [zicht/standards-php#21]
```
 802 | WARNING | Usage of numbers in methodname "isUnder26" is discouraged
| | (Zicht.NamingConventions.Functions.MethodNaming)
811 | WARNING | Usage of numbers in methodname "setUnder26" is discouraged
| | (Zicht.NamingConventions.Functions.MethodNaming)
```

I cannot see why this is even throwing warnings, that method names should not contain obscure names with just digits is something we all can agree on, but this rule has to go imho

**Comment by muhammedeminakbulut** [comment]
decided to allow numbers in method names as long as the name does not start with a number.
