### ISSUE TITLE
Enforce order of variables in docblocks

### ISSUE THREAD

**Issue by wtfzdotnet** [zicht/standards-php#22]
Given the following example (truncated);

```php
    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $var;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @var string
     */
    private $var2;
```

The order of @var for example and other annotations should be something to be considered in my opinion, as it looks messy if throughout all files the order of this changes. Not a deal breaker, but could be neater :+1:

**Comment by boudewijn-zicht** [comment]
If and when we pick this up, we should also include newlines, do we or do we not want new lines between annotations?

```
```php
    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    private $var;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @deprecated
     * @var string
     */
    private $var2;
```

**Comment by 7ochem** [comment]
Voorstel voor regels toevoegen
