### ISSUE TITLE
Strict comparison

### ISSUE THREAD

**Issue by DoNormal** [zicht/standards-php#23]
There's no compiler in PHP so let's pretend we're working type-safe by checking for usage of `==` and `!=` instead of `===` and `!==`.

**Comment by boudewijn-zicht** [comment]
I prefer using `===` and `!==` where possible, but there will be cases where you will want and need to the non-type specific ones instead.  So I am hesitant to make this into a hard rule.

**Comment by pbergman** [comment]
i didn`t wanted to debate on public forums but why? those are totally different and both should not be compared as doing the same. Because for example this works when no matches or a error:

```
if (false == preg_match....
```

as for:

```
if (false === preg_match....
```

only run when regex has a error. There are allot of those methods that work on the same principle.

**Comment by DoNormal** [comment]
> there will be cases where you will want and need to the non-type specific ones instead. So I am hesitant to make this into a hard rule.

Could you elaborate what these cases are? (There's always `@codingStandardsIgnoreStart` if you _really_ know what you're doing.)

> i didn`t wanted to debate on public forums

Well here we are.

> but why

For type-safety, which leads to code that's less unpredictable.

> `if (false === preg_match....` only run when regex has a error. 

As it should. If you to check for the number of matches, you should use `preg_match === 0`. The [documentation of `preg_match`](http://php.net/manual/en/function.preg-match.php) even says so: 

> Use the === operator for testing the return value of this function.

**Comment by pbergman** [comment]
>As it should. If you want to check for the absence of matches, you should use preg_match === 0. The documentation of preg_match even says so:

but you don`t wanted to have the `===` comparison? And there are cases you don`t care about errors and should behave the same as no matches and thus you should check `false == preg_match`

Another great example is the `array_search` function, the normal syntax could be:

```
if (false !== $index = array_search('foo', $array)) {
     unset($array[$index])
} else {
      echo "key $index does not exist."
}
```

but in my opinion, those are two comparisons are totally different things and should not be compared with each other.

**Comment by 7ochem** [comment]
I still havent formed an opinion on this :smile: 

I'd like to add that if you need loose comparison, you could still use strict comparison when casting values:

```php
if (0 === (int)preg_match(......)) {
```
This would enter the if-statement when `preg_match()` returns `false` on failure and the result of `0` matches. The advantage of this is that it will become clear to you that this is done intentionally by the original programmer in opposite to the non-strict comparison version.

Having strict comparison by rule is fine and all, but the world of PHP is filled with non-strict everywhere. What will you do with that?

This is not very strict, so you would have to catch that too in your rule:
```php
$foo = getMeSomething();
if ($foo) {
```
`$foo` could be `null`, `0`, `false`, `[]` or `''`

`isset()` is also not "strict":
```php
$foo = null;
var_dump($foo, $bar);
// bool(false)
// bool(false)

$bar = ['a' => null];
var_dump(isset($bar['a']), isset($bar['b']));
// bool(false)
// bool(false)
```

**Comment by 7ochem** [comment]
I found an argument against it today:

Value Objects. Consider having a `Money` value object with an amount and a currency (as properties). You should be able to loosely compare them with `$x == $y`: it is not the exact same object (`$x` and `$y` do not reference the same value), but both are separate objects of the same type with the same values.

Strict comparison (`$x === $y`) would only evaluate to `true` if both are pointing the exact same object (`$x = new Object(); $y = $x`)

```
$m1 = new Money(100, 'EUR');
$m2 = new Money(100, 'EUR');
$m3 = new Money(100, 'USD');

var_dump($m1 == $m2); // => true
var_dump($m1 == $m3); // => false
```

https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/#value-objects
