### ISSUE TITLE
assignment in if statement

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/standards-php#5]
It is undesireable to have assignments in if statements.

**Comment by pbergman** [comment]
don`t agree, this is normal practice in php and can not see why this would give any problems?

**Comment by DoNormal** [comment]
- It's error-prone.
- It's difficult to see if the assignment was intentional.
- It's a feature in JavaScript as well, but we have ESLint rules that disallow it. If we think it's bad in JS, it's strange to say it's alright in PHP.

**Comment by boudewijn-zicht** [comment]
I woud like to allow one assignment in an `if` statement, I find it to be a very convenient php feature. 
 However, I do not like more than one assignment in an `if` statement, that quickly becomes messy.

:white_check_mark: `if ($foo = $this->getFoo()) { ... }`
:red_circle: `if (($foo = $this->getFoo()) && ($bar = $this->getBar())) { ... }`

**Comment by wpbenner** [comment]
I agree that it's undesireable to have a asign statement in a if statement. The if statement is a check a state not to asign you variables. It's cleaner to use the if statement to check the state of your variables. "Clean code"

**Comment by pbergman** [comment]
i disagree, this could all be solved with getting a better color scheme in your IDE (or better testing) and also should not have any part in here.

and syntax like `return is_null($foo) ? "yes" : "no"`  or `$foo = $item ?: "default";` is basically the same syntax applies to same rule you mention above, so should we disallow them also?

**Comment by wtfzdotnet** [comment]
*Downvote*, this behavior is valid and should thus be allowed.

> It's a feature of JavaScript as well, but still we have ESLint rules that disallow it. If we think it's bad in JS, it would be strange to say it's alright in PHP.

@DoNormal , Different language, different rules, I don't see why this should be a problem. 

> I woud like to allow one assignment in an if statement, I find it to be a very convenient php feature.
> However, I do not like more than one assignment in an if statement, that quickly becomes messy.

I do agree with @boudewijn-zicht on the fact that having multiple of these should be disallowed, as it is still a shortcut like the ternary operator works, like @pbergman said.

**Comment by muhammedeminakbulut** [comment]
only error with multiple assignments in if statement. decided with the core dev team
