### ISSUE TITLE
Make " Found long type name "integer" " fixable

### ISSUE THREAD

**Issue by erik-zicht** [zicht/standards-php#68]
Found long type name "integer". Use short type "int" for type definition in `@var` tag for property

Could this be a fixable warning?

**Comment by 7ochem** [comment]
@erik-zicht I think it can, but I figured it would take quite some dev time so I hadn't done it while I was writing the sniff in the first place.

The sniff also detects types within more complex definition, for example: `@var (null|integer|string)[]`. So for a "fixer" I need to write something to keep track of the original position within the definition string while processing each of the types.
