### ISSUE TITLE
Line exceeds 120 characters: up line length

### ISSUE THREAD

**Issue by boudewijn-zicht** [zicht/standards-php#69]
For earlier discussion, see #47 

Applying this ruleset on `zicht/sro-bundle` there are 209 issues with this rule.  That makes it quite difficult to find usefull warnings.

I would like to propose upping the value significantly, i.e. 512.  That way we can decide what is best for our case while still being notified of excesses.

**Comment by 7ochem** [comment]
Is this the only package this is an issue? Are there any other?
It is also possible to configure this specific rule differently within this package

**Comment by boudewijn-zicht** [comment]
I am pretty sure that other packages have similar issues, let alone all the project code...

I wouldn't mind ignoring this specific rule, but I am pretty sure that will result in everyone doing the same.  Given that assumption I would rather remove warning and only give an error on excessively long lines, as was decided in an earlier poll, see https://github.com/zicht/standards-php/issues/47

**Comment by erik-zicht** [comment]
We still follow and do exactly as proposed in https://www.php-fig.org/psr/psr-2/#23-lines and discussed in #47. 

We could:
* run jenkins-builds with `composer run-script lint -- --warning-severity=0` and locally without, to still see all warnings
* re-evaluate and propose to drop the soft limit and not follow PSR-2 (which is basically option nr 3 in the poll :grimacing:)

**Comment by 7ochem** [comment]
What I want to see first here is if there are other packages or projects that are so heavily affected like the mentioned one. And then see if we need to change the rule. My personal opinion has been to set a limit, but not as low as 120. Just **a** limit to have something going off when it is really wrong. So this would be the same as proposed here, to set it to 512. The goal is to have a rule on which most of us agree and most code will pass. If there's any exceptional code, we should see if we can make an exception on the rule, not just change rules immediately.

One question of @boudewijn-zicht was who decided upon this rule. It was voted for and final decision was done in the dev meeting. I think, if we were to loosen this rule it doesn't need to be discussed broadly as putting up the restriction in the first place.

**Comment by boudewijn-zicht** [comment]
The 120 character line limit warning occurs...
- zicht/sro: 146 times
- zicht/sro-bundle: 210 times
- zicht/ticket-trigger-culture: 210 times (these are not the same 210 from the sro-bundle, though the coincidence is surprising)

**Comment by 7ochem** [comment]
Ok, that's an argument to propose a change :smile: 

What is the max length used in those projects? (the warning says something like "Line exceeds 120 characters; contains **154** characters")

**Comment by boudewijn-zicht** [comment]
I glanced at the output.  I guestimate that around 70% is in the range 130-140 characters long, 30% in the range 140-200.  I spotted on case where it was 240 characters ish long.

**Comment by erik-zicht** [comment]
Up limit to 256 to spot excesses?

**Comment by 7ochem** [comment]
Make it ERROR or still throw a WARNING?

**Comment by erik-zicht** [comment]
I'm tempted to choose the second option...

**Comment by boudewijn-zicht** [comment]
I prefer the second option as well.  Warning on 256, error on 512.
