### ISSUE TITLE
enforce array short notation

### ISSUE THREAD

**Issue by muhammedeminakbulut** [zicht/standards-php#7]
enforce array short notation `[]` instead of `array()`

**Comment by pbergman** [comment]
this would break BC so should not be enforced!

**Comment by muhammedeminakbulut** [comment]
I don't see why we should support unsupported PHP versions? Could you explain that?

**Comment by pbergman** [comment]
because we still maintain projects where on the server php 5.3 is installed, and the notation is still supported a later versions.

**Comment by wpbenner** [comment]
@pbergman Nice example! But how long are we going to unsupported versions? Because 5.3 has security problems in the long run. Does that mean we need to halt progress because we don't update php versions? Mabey it's a good thing to put in the SLA and talk about it with the management.

**Comment by boudewijn-zicht** [comment]
@pbergman Which of our servers still use older php? If they can not be upgraded, and still require maintenance with newer bundles, that would definitely change this discussion.

**Comment by muhammedeminakbulut** [comment]
**sidenote this is a public discussion. do not post data that could compromise customer data :)**

**Comment by muhammedeminakbulut** [comment]
decided to enforce with the dev team will trigger an error.

**Comment by muhammedeminakbulut** [comment]
`Generic.Arrays.DisallowLongArraySyntax.Found` is the one
