### ISSUE TITLE
Reconsider allowance of {@inheritDoc}

### ISSUE THREAD

**Issue by 7ochem** [zicht/standards-php#71]
As per PhpStorm 2019.1 the autosuggest for `{@inherit` shows `{@inheritDoc}` with capital `D` only. Also any generated doc blocks will use this variant.

This was done because it was reported as [bug here as WI-34826](https://youtrack.jetbrains.com/issue/WI-34826) and also references [the official PhpDoc docs](https://docs.phpdoc.org/guides/inheritance.html)

Clearly _"inheritDoc"_ is the only correct camel casing of _"inherit doc"_

I think it would be wise to allow both `{@inheritdoc}` and `{@inheritDoc}`. This would introduce inconsistency, but allows flexibility and doesn't break old code and the new PhpStorm implementation.

(To be clear, this does not suggest to allow `@inheritDoc` or any other form without curly braces)

**Comment by boudewijn-zicht** [comment]
I would prefer only allowing `{@inheritDoc}`.  With the same arguments that I preferred only allowing `{@inherritdoc}` before.

This should not have major impact as the auto-fixer will do all the work for us.

**Comment by erik-zicht** [comment]
https://docs.phpdoc.org/guides/inheritance.html#the-inheritdoc-tag

**Comment by erik-zicht** [comment]
I would suggest the same, we go back to allowing only `{@inheritDoc}`
