### ISSUE TITLE
Docstring style for class variables

### ISSUE THREAD

**Issue by boudewijn-zicht** [zicht/standards-php#76]
We are using three different styles in our code, do we want to force one of these?

```php
class StyleShort
{
    /** @var null|string This is an optional description */
    private $foo;

    /** @var null|string */
    private $bar;
}

class StyleLong
{
    /**
     * @var null|string This is an optional description
     */
    private $foo;

    /**
     * @var null|string
     */
    private $bar;
}

class StyleWithoutLines
{
    /**
     * @var null|string This is an optional description
     */
    private $foo;
    /**
     * @var null|string
     */
    private $bar;
}
```

`StyleShort` places the docstring on a single line.
`StyleLong` places the docstring on three lines.
`StyleWithoutLines` does not have a newline between parameters.

The current linter and php-storm allows all styles.  If we choose one, then we can probably make the phpcs linter auto-fix it into the style we want.

**Comment by boudewijn-zicht** [comment]
I vote for the `StyleShort` option.

**Comment by 7ochem** [comment]
> I vote for the `StyleShort` option.

There is an "if" there: What if the property has more than 1 annotation?

```
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
```

I also vote for `StyleShort` (if there is the one mandatory `@var` only), so with one empty line in between please!

**Comment by 7ochem** [comment]
Closing as friendsofphp/php-cs-fixer is the preferred linter now and zicht/standards-php is abandoned.
